site_name: Dutch Wild West
repo_url: https://github.com/lucajjj/dutchwildwestapv/tree/gh-pages
theme:
  name: material
  language: nl
  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/git-alt 
  plugins:
    - offline
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
        primary: black
    - scheme: slate 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
nav:
  - Home: "index.md"
  - Algemene Regels: "algemeneregels.md"
  - Strafbepaling: "strafbepaling.md"
  - Algemene Plaatselijke Verordening: "apv.md"
  - Belastingen: "belastingen.md"
  - Het Wetboek: "Wetboek.md"
extra_css:
  - stylesheets/extra.css